apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-app
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: alert-app
    spec:     # pod spec
      containers:
      - name: alert-app
        image: us.icr.io/bokai-cr/alert-app-node
        ports:
        - containerPort: 3000
---

kind: Service
apiVersion: v1
metadata:
  name: alert-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31001
  selector:
    app: alert-app
